<a href="https://colab.research.google.com/github/xulisong1/test1/blob/master/src/Untitled76.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


In [0]:
import tensorflow as tf
import tensorflow.linalg as tfla
import numpy as np
import numpy.linalg as npla

In [0]:
sess = tf.Session()

In [15]:
#build a graph
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b



#launch a graph in a session.
sess = tf.compat.v1.Session()

# evaluate the tensor 'c'.
print(sess.run(c))


30.0


In [0]:
sess.close()

In [0]:
sess = tf.compat.v1.Session(config = tf.compat.v1.ConfigProto(allow_soft_placement = True, log_device_placement = True))

In [22]:
a = tf.constant([[1.,-1.,0],[0.,2.,0.],[0.,0.,1.]])
sess.run(a)

array([[ 1., -1.,  0.],
       [ 0.,  2.,  0.],
       [ 0.,  0.,  1.]], dtype=float32)

In [21]:
#identity matrix
id3 = tf.eye(3)
sess.run(id3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [23]:
#transpose
a_trans = tfla.transpose(a)
sess.run(a_trans)

array([[ 1.,  0.,  0.],
       [-1.,  2.,  0.],
       [ 0.,  0.,  1.]], dtype=float32)

In [24]:
#multiplication
prod = a @ a_trans
sess.run(prod)

array([[ 2., -2.,  0.],
       [-2.,  4.,  0.],
       [ 0.,  0.,  1.]], dtype=float32)

In [26]:
prod1 = a @ id3
sess.run(prod1)

array([[ 1., -1.,  0.],
       [ 0.,  2.,  0.],
       [ 0.,  0.,  1.]], dtype=float32)

In [25]:
soln = tfla.solve(a, id3)
sess.run(soln)

array([[1. , 0.5, 0. ],
       [0. , 0.5, 0. ],
       [0. , 0. , 1. ]], dtype=float32)

In [27]:
#determinant
a_det = tfla.det(a)
sess.run(a_det)

2.0

In [28]:
#inverse
a_inv = tfla.inv(a)
sess.run(a_inv)

array([[1. , 0.5, 0. ],
       [0. , 0.5, 0. ],
       [0. , 0. , 1. ]], dtype=float32)

In [29]:
#change tensor to numpy array

a_np = sess.run(a)

type(a_np)

numpy.ndarray

In [30]:
a_eig_val, a_eig_vec = npla.eig(a_np)
print(a_eig_val)
print(a_eig_vec)

[1. 2. 1.]
[[ 1.         -0.70710677  0.        ]
 [ 0.          0.70710677  0.        ]
 [ 0.          0.          1.        ]]
